import Head from "next/head";
import HomeDarkAnimation from "../views/all-home-version/HomeDarkAnimation";

export default function Home() {
  return (
    <>
      <Head>
        <title>KASHRIFF || Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ScrollToTop /> */}
      <HomeDarkAnimation />
    </>
  );
}
